language: java
branches:
  only:
  - master
  - /^\d+\.\d+$/
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/io/vertx/
jobs:
  include:
    - stage: test
      name: "OpenJDK 8"
      jdk: openjdk8
      script: mvn -q clean verify -B
    - if: type != pull_request
      name: "OpenJDK 11"
      jdk: openjdk11
      script: mvn -q clean verify -B
    - stage: deploy
      name: "Deploy to Sonatype's snapshots repository"
      jdk: openjdk8
      if: type != pull_request AND env(SONATYPE_NEXUS_USERNAME) IS present
      script: bash .travis.deploy.artifacts.sh
notifications:
  email:
    recipients:
      - secure: "ZI9hCdCe/5SgvFCxBkyvaNIAgtbmXJh+UI6LHhoIgYCsU3Hae7H/kEnW/jN+BfvgzqRe8CkcYgbL+zKyolpqbHELX/v5TL5pmJXsX0TnlYCW+DRBID4C9ukP7ro134jaQLDE1lyhzs/FF/RxBN433H/Ass7TmCpyo/u2/3cDAso="
    on_success: always
    on_failure: always
